movie_rental/api/urls.py
from pydoc import cli
from django.urls import path
from .views import cliente, pelicula, renta

urlpatterns = [
    path('', pelicula.home),
    
    path('cliente/', cliente.clientes_all),
    path('cliente/add/', cliente.add_customer),
    path('cliente/<int:client_pk>/', cliente.view_customer_details),
    path('cliente/<int:client_pk>/update/', cliente.edit_customer_details),
    path('cliente/<int:client_pk>/delete/', cliente.delete_customer),

    path('pelicula/', pelicula.peliculas),
    path('pelicula/add/', pelicula.agregar_pelicula), # API 1: Add new cars
    path('pelicula/<int:pelicula_pk>/', pelicula.detalle_peliculas),
    path('pelicula/<int:pelicula_pk>/active_booking/', pelicula.detalle_renta_peliculas), # API 3: Show details of pelicula with booking details
    path('pelicula/<int:pelicula_pk>/update/', pelicula.editar_pelicula),
    path('pelicula/<int:pelicula_pk>/delete/', pelicula.eliminar_pelicula),

    path('renta/', renta.rentas_all),
    # path('renta/book/', renta.), # API 2: Book an available pelicula
    path('renta/<int:renta_pk>/', renta.ver_renta),
    # path('renta/<int:renta_pk>/extend/', renta.extend_reservation_date), # API 5: Extend date of renta.
    path('renta/<int:renta_pk>/cancel/', renta.cancelar_renta), # API 6: Cancel Specific booking

    # path('pelicula/status/', pelicula.pe) # API 4: Show cars with availability status on given date.

]

movie_rental/movie_rental/urls.py
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib import admin
from django.urls import path, include

schema_view = get_schema_view(
   openapi.Info(
      title="Api TEST",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="raudalesgo@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redocs/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

movie_rental/api/models.py
from django.db import models

class Cliente(models.Model):
    nombre = models.CharField('Nombre',max_length=255)
    email = models.EmailField('Email',max_length=255)
    celular = models.CharField('Celular',max_length=20)
    
    class Meta:
        ordering = ['nombre','email','celular']

    def __str__(self):
        return self.nombre


class Pelicula(models.Model):
    titulo = models.CharField('Titulo',max_length=20)
    descripcion = models.CharField('Descipcion',max_length=50)
    renta_por_dia = models.IntegerField('Renta_por_dia')
    disponible = models.BooleanField('Disponible',null=True)

    def __str__(self):
        return self.titulo


class Renta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE)
    dia_renta = models.DateField()
    dia_devolucion = models.DateField()

    def __str__(self):
        return str(self.cliente) + "- " + str(self.pelicula)
    
    def get_data(self):
        return {
            'id': self.id,
            'cliente': self.cliente,
            'email': self.email,
            'fecha_renta' : self.fecha_renta,
            'fecha_devolucion': self.fecha_devoluacion
        }

movie_rental/api/forms.py
from django import forms
from .models import Pelicula, Cliente, Renta


class PeliculaForm(forms.ModelForm):
    class Meta:
        model = Pelicula
        fields = ['titulo', 'descripcion', 'renta_por_dia','disponible']
        widgets = {'titulo': forms.TextInput(attrs={'class': 'form-control'}),
                   'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
                   'renta_por_dia': forms.IntegerField(),
                   'disponible': forms.BooleanField( required=True),
                   }


# class ClienteForm(forms.ModelForm):
#     class Meta:
#         model = Cliente
#         fields = ['nombre', 'apellido', 'fecha_nacimiento','direccion', 'telefono', 'correo']
#         widgets = {'nombre': forms.TextInput(attrs={'class': 'form-control'}),
#                    'apellido': forms.TextInput(attrs={'class': 'form-control'}),
#                    'fecha_nacimiento': forms.DateInput(format=('%d-%m-%y'), attrs={'class': 'form-control',
#                                                                                  'placeholder': 'Select a date',
#                                                                                  'type': 'date'
#                                                                                  }),
#                    'direccion': forms.TextInput(attrs={'class': 'form-control'}),
#                    'telefono': forms.TextInput(attrs={'class': 'form-control'}),
#                    'correo': forms.EmailInput(attrs={'placeholder': ('Email')})
#         }

# class RentaForm(forms.ModelForm):
#     class Meta:
#         model = Renta
#         fields = ['valor', 'fecha_alquiler', 'fecha_devolucion', 'cliente' , 'pelicula']
#         # def __init__(self, *args, **kwargs):
#         # pelicula = kwargs.pop('pelicula','')
#         # super(DocumentForm, self).__init__(*args, **kwargs)
#         # self.fields['user_defined_code']=forms.ModelChoiceField(queryset=UserDefinedCode.objects.filter(owner=pelicula))
#         widgets = {'valor': forms.TextInput(attrs={'class': 'form-control' }),
#                    'fecha_alquiler': forms.DateInput(format=('%d-%m-%y'), attrs={'class': 'form-control',
#                                                                                  'placeholder': 'Select a date',
#                                                                                  'type': 'date'
#                                                                                  }),
#                    'fecha_devolucion': forms.DateInput(format=('%d-%m-%y'), attrs={'class': 'form-control',
#                                                                                    'placeholder': 'Select a date',
#                                                                                    'type': 'date'
#                                                                                    }),

                   
#                    }

movie_rental/api/views/cliente.py
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from api.models import Cliente
from api.serializers import ClienteSerializer


@api_view(['GET'])
def clientes_all(request):

    if request.method == 'GET':
        clientes = Cliente.objects.all()
        serializer = ClienteSerializer(clientes, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def view_customer_details(request, client_pk):
    try:
        cliente = Cliente.objects.get(pk=client_pk)
    except cliente.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ClienteSerializer(cliente)
        return Response(serializer.data)


@api_view(['POST'])
def add_customer(request):
    if request.method == 'POST':
        serializer = ClienteSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
def edit_customer_details(request, client_pk):
    try:
        cliente = Cliente.objects.get(pk=client_pk)
    except Cliente.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        serializer = ClienteSerializer(cliente, data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
def delete_customer(request, client_pk):
    try:
        cliente = Cliente.objects.get(pk=client_pk)
    except Cliente.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'DELETE':
        cliente.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

movie_rental/api/views/pelicula.py
from collections import namedtuple
from datetime import datetime, date
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q
from rest_framework import status
from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from api.forms import PeliculaForm 

from api.models import Pelicula, Renta
from api.serializers import (PeliculaSerializer)


@api_view(['GET'])
def home(request):

    if request.method == 'GET':
        data = [{'message':'Bienvenido a la renta de Peliculas'}]
        # return JsonResponse(data, safe=False)
        return render(data, 'templates/show.html')


@api_view(['GET'])
def peliculas(request):

    if request.method == 'GET':
        peliculas = Pelicula.objects.all()
        serializer = PeliculaSerializer(peliculas, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def detalle_peliculas(request, pelicula_pk):

    try:
        peliculas = Pelicula.objects.get(pk=pelicula_pk)
    except Pelicula.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = PeliculaSerializer(peliculas)
        return Response(serializer.data)


@api_view(['GET'])
def detalle_renta_peliculas(request, pelicula_pk):

    try:
        peliculas = Pelicula.objects.get(pk=pelicula_pk)
    except Pelicula.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        fecha_actual = date.today()
        Pelicula_detalle = namedtuple('Pelicula_detalle',('pelicula','rentas_actual'))

        # Conditions for filtering only currently active bookings of a particular car
        # suffix "__gte" stands for Greater Than or Equal to.
        condition_1 = Q(dia_renta__gte=fecha_actual)
        condition_2 = Q(dia_devolucion__gte=fecha_actual)

        pelicula_detalle = Pelicula_detalle(
            car = peliculas,
            current_active_bookings = Renta.objects.filter(car=pelicula_pk).filter(condition_1 | condition_2),
        )
        serializer = Pelicula_detalle(pelicula_detalle)
        return Response(serializer.data)


@api_view(['POST'])
def agregar_pelicula(request):

    if request.method == 'POST':
        serializer = PeliculaSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['PUT'])
def editar_pelicula(request, pelicula_pk):

    try:
        peliculas = Pelicula.objects.get(pk=pelicula_pk)
    except Pelicula.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        serializer = PeliculaSerializer(peliculas, data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE'])
def eliminar_pelicula(request, pelicula_pk):

    try:
        peliculas = Pelicula.objects.get(pk=pelicula_pk)
    except Pelicula.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'DELETE':
        peliculas.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

movie_rental/api/views/renta.py
import json
from datetime import date
from urllib import response

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import JsonResponse
from api.models import Renta
from api.serializers import RentaSerializer


@api_view(['GET'])
def rentas_all(request):

    if request.method == 'GET':
        rentas = Renta.objects.all()
        serializer = RentaSerializer(rentas, many=True)
        return Response(serializer.data)
    
    def rentas(request):
        rentas = Renta.objects.all()
        data = [rentas.get_data() for renta in rentas]
        response = {'data': data}
        return JsonResponse(response)


@api_view(['GET'])
def ver_renta(request, renta_pk):

    try:
        reservation = Renta.objects.get(pk=renta_pk)
    except Renta.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = RentaSerializer(reservation)
        return Response(serializer.data)


# @api_view(['POST'])
# def book_car(request):
#     """
#     API endpoint for booking an available car.
#     """
#     if request.method == 'POST':
#         serializer = RentaSerializer(data=request.data)
            
#         if serializer.is_valid():
#             current_date = date.today()
#             issue_date = serializer.validated_data['issue_date']
#             return_date = serializer.validated_data['return_date']

#             car = serializer.validated_data['car']
#             rentas = Renta.objects.all().filter(car=car.id)

#             # Check if the issue_date of new reservation doesn't clash with any previous rentas
#             for r in rentas:
#                 if r.issue_date <= issue_date <= r.return_date:
#                     content = {"message":"The selected car is not available on this date"}
#                     return Response(data=json.dumps(content), status=status.HTTP_400_BAD_REQUEST)

#             # Check whether issue_date is not older than today's date, and is less equal to return_date
#             if current_date <= issue_date and issue_date <= return_date:
#                 serializer.save()
#                 return Response(serializer.data, status=status.HTTP_201_CREATED)

#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['DELETE'])
def cancelar_renta(request, renta_pk):

    try:
        reservation = Renta.objects.get(pk=renta_pk)
    except Renta.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'DELETE':
        reservation.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

movie_rental/api/templates/alquilerPeliculas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
     <h1>Gestion de peliculas</h1>

</body>
</html>

movie_rental/api/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<meta charset="UTF-8">  
<title>{% block title %}{% endblock %}</title>
{% load static %}  
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"/>
<link rel = "stylesheet" type = "text/css" href = "https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
</head> 
<body>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>
 
<script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src = "https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 5
       } 
    );
} );
</script>
</body> 
</html>

movie_rental/api/templates/datatable.html
{% extends "datatable/base.html" %}

{% block content %}
    <table id="myStaticDatatable">
        <thead>
        <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Pelicula</th>
            <th>Fecha de Devolucion</th>
            <th>Fecha de Retorno</th>
        </tr>
        </thead>
        <tbody>
        {% for renta in rentas %}
            <tr>
                <td>{{ renta.id }}</td>
                <td>
                    {{ rentas.cliente }}
                    <br>
                    {{ pelicula.nombre }} {{ pelicula.descripcion }} 
                </td>
                <td>
                    {{ cliente.nombre }}
                    <br>{{ cliente.celular }}
                    {{ cliente.email }}
                </td>
                <td>{{ pelicula.renta_por_dia }}</td>
                <td>{{ pelicula.disponible }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block extra_js %}
    <script>
        $(document).ready(function () {
            $('#myStaticDatatable').DataTable();
        });
    </script>
{% endblock %}

movie_rental/api/templates/edit.html
{% extends "base.html" %}
  
{% block title %}Agregar nueva pelicula{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{pelicula.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Actualizar Detalles</h3>  
        </div> 
        <div class="mb-3"> 
            <label>pelicula ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ pelicula.id }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Nombre:</label>  
            <input type="text" class="form-control" name="nombre" id="id_nombre" required maxlength="100" value="{{ pelicula.nombre }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Sinopsis:</label>  
            <input type="text" class="form-control" name="sinopsis" id="id_sinopsis" required maxlength="254" value="{{ pelicula.sinopsis }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Categoria:</label>  
            <input type="text" class="form-control" name="categoria" id="id_categoria" required maxlength="15" value="{{ pelicula.categoria }}" />  
        </div> 
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Actualizar</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}   

movie_rental/api/templates/edit_cliente.html
{% extends "base.html" %}
  
{% block title %}Editar cliente{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/updateCliente/{{cliente.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Actualizar Detalles</h3>  
        </div> 
        <div class="mb-3"> 
            <label>Nombre:</label>  
            <input type="text" class="form-control" name="nombre" id="id_nombre" required maxlength="100" value="{{ cliente.nombre}}"/>    
        </div> 
        <div class="mb-3"> 
            <label>apellido:</label>  
            <input type="text" class="form-control" name="apellido" id="id_apellido" required maxlength="100" value="{{ cliente.apellido }}" />  
        </div> 
        <div class="mb-3"> 
            <label>fecha de Nacimiento:</label>  
            <input type="text" class="form-control" name="fecha_nacimiento" id="id_fecha_nacimiento" required maxlength="254" value="{{ cliente.fecha_nacimiento }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Direccion:</label>  
            <input type="text" class="form-control" name="direccion" id="id_direccion" required maxlength="15" value="{{ cliente.direccion }}" />  
        </div>
        <div class="mb-3"> 
            <label>telefono:</label>  
            <input type="text" class="form-control" name="telefono" id="id_telefono" required maxlength="15" value="{{ cliente.telefono }}" />  
        </div> 
        <div class="mb-3"> 
            <label>correo:</label>  
            <input type="text" class="form-control" name="correo" id="id_correo" required maxlength="15" value="{{ cliente.correo }}" />  
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Actualizar</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}   

movie_rental/api/templates/edit_renta.html
{% extends "base.html" %}
  
{% block title %}Editar Rentas{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{renta.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Actualizar Detalles</h3>  
        </div> 
        <div class="mb-3"> 
            <label>Renta ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ renta.id }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>valor:</label>  
            <input type="text" class="form-control" name="nombre" id="id_nombre" required maxlength="100" value="{{ renta.valor }}" />  
        </div> 
        <div class="mb-3"> 
            <label>fecha_alquiler:</label>  
            <input type="text" class="form-control" name="sinopsis" id="id_sinopsis" required maxlength="254" value="{{ renta.fecha_alquiler }}" />  
        </div> 
        <div class="mb-3"> 
            <label>fecha_devolucion:</label>  
            <input type="text" class="form-control" name="categoria" id="id_categoria" required maxlength="15" value="{{ renta.fecha_devolucion }}" />  
        </div> 
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Actualizar</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}   

movie_rental/api/templates/index.html
{% extends "base.html" %}
  
{% block title %}Peliculas{% endblock title %}
  
{% block content %}
<div class="col-md-12">    
    <form method="POST" class="post-form" action="/addnew">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Ver detalles</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>Nombre:</label>  
            {{ form.nombre }}   
        </div> 
        <div class="mb-3"> 
            <label>Sinopsis:</label>  
            {{ form.sinopsis }}   
        </div>  
        <div class="mb-3"> 
            <label>Categoria:</label>  
            {{ form.categoria }}   
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">aceptar</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 

movie_rental/api/templates/index_clientes.html
{% extends "base.html" %}
  
{% block title %}Administracion de Clientes{% endblock title %}
  
{% block content %}
<div class="col-md-12">    
    <form method="POST" class="post-form" action="/addnewCliente">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Ver detalles de clientes</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>Nombre:</label>  
            {{ form.nombre }}   
        </div> 
        <div class="mb-3"> 
            <label>Apellido:</label>  
            {{ form.apellido }}   
        </div> 
        <div class="mb-3"> 
            <label>fecha nacimiento:</label>  
            {{ form.fecha_nacimiento }}   
        </div>  
        <div class="mb-3"> 
            <label>Direccion:</label>  
            {{ form.direccion }}   
        </div>
        <div class="mb-3"> 
            <label>Telefono:</label>  
            {{ form.telefono }}   
        </div>
        <div class="mb-3"> 
            <label>Correo:</label>  
            {{ form.correo }}   
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">Aceptar</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 

movie_rental/api/templates/index_renta.html
{% extends "base.html" %}
  
{% block title %}Rentar una nueva pelicula{% endblock title %}
  
{% block content %}
<div class="col-md-12">    
    <form method="POST" class="post-form" action="/renta/">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Ver detalles</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>valor:</label>  
            {{ rentas.cliente }}   
        </div> 
        <div class="mb-3"> 
            <label>Fecha Alquiler:</label>  
            {{ rentas.pelicula }}   
        </div>  
        <div class="mb-3"> 
            <label>Fecha Devolucion:</label>  
            {{ rentas.dia_renta }}   
        </div>
        <div class="mb-3"> 
            <label>Fecha Devolucion:</label>  
            {{ rentas.fecha_devolucion }}   
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">aceptar</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 

movie_rental/api/templates/show.html
{% extends "base.html" %}
  
{% block title %}Pelicula Records{% endblock title %}
  
{% block content %}
 <div class="col-md-12">
        </br>
        <div class="form-group">
            <span><a href="/addnew" class="btn btn-success">Agregar Pelicula</a></span>   
            <span><a href="/" class="btn btn-primary">Administracion de Rentas</a></span> 
            <span><a href="/indexCliente" class="btn btn-primary">Clientes Registrados</a></span>  
        </div>
        </br>
        <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>Nombre de la Pelicula</th>
            <th>Sinopsis</th>
            <th>Categoria</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </thead>
        <tbody>
        {% for pelicula in pelicula %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ pelicula.id }}</td>  
            <td>{{ pelicula.titulo }}</td>  
            <td>{{ pelicula.descripcion}}</td>  
            <td>{{ pelicula.renta_por_dia }}</td>  
            <td>{{ pelicula.disponible }}</td>  
            <td><a href="/edit/{{ pelicula.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/delete/{{ pelicula.id }}" class="btn btn-danger">Delete</a></td>  
            </tr>  
        {% endfor %} 
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}